### ISSUE TITLE
Automated test framework

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#22]
We should have some kind of automated test framework. We already do have tests, but by "automated", I mean that a simple `make tests` should run all the tests. That would simplify testing HolBA, prevent regressions and enable CI in the future (that's easy and free on GitHub with, e.g., Travis (that's what HOL uses)).

I think that's shouldn't be difficult to set up :slightly_smiling_face:

**Comment by andreaslindner** [comment]
Yes, that is indeed a very good idea and I'm thankful for your perseverance! I took a look at it now and I see that we need to use the Travis caching features properly because of our long build time. Our HOL4 dependency can be built to a cache and then we have a 50 minute build and test limit for HolBA. It would be good to be able to keep it within this time anyways.

I don't know whether they have a build frequency limit as well.

Anyhow, we could possibly complement this with more comprehensive tests on one of our machines that are running less rigorously and less frequently for example. I think about something like once a day and if the connection doesn't work one day it wouldn't be a problem.
