### ISSUE TITLE
Wrong SMLFILES in some Holmakefile.gen

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#28]
This seems wrong, and appear in some `Holmakefile.gen`:

```makefile
SMLFILES   = $(patsubst %Script.sml,%Theory.uo,$(wildcard *.sml))
```

**Comment by didriklundberg** [comment]
This little thing is really old, I think this was added to the Holmakefiles in commit ba69eeb8640ae387a4398032a4dba0ddddea8b80 back in 2017 and then just copied from there. I remember scowling at this, but I didn't bother with it since everything seemed to work anyway.

**Comment by andreaslindner** [comment]
Now I'm not following. What exactly is wrong with it?

**Comment by didriklundberg** [comment]
> Now I'm not following. What exactly is wrong with it?

See the documentation of patsubst [here](https://www.gnu.org/software/make/manual/html_node/Text-Functions.html).

Now, consider this snippet from the Holmake.gen file in the `exec` tool:

```
SMLFILES   = $(patsubst %Script.sml,%Theory.uo,$(wildcard *.sml))

TARGETS = $(patsubst %.sml,%.uo,$(SMLFILES))
```

The code in question matches all .sml files, from these replaces all Script.sml suffixes with Theory.uo. Then, in all files resulting from that operation, replaces .sml with .uo.

The other approach I have seen in the files is to first replace "Script" with "Theory", and then all .sml endings with .uo. Both approaches work, but we should settle for one of them I think, so that the files don't appear at a glance to be purposefully designed to do different things.

Like I wrote above, it doesn't seem to make a difference that the SMLFILES variable is different, since I don't think that is used other than to define TARGET in any of the makefiles.

**Comment by totorigolo** [comment]
You're right, since `SMLFILES` is only used in `TARGET` it doesn't make a difference. But as you said, we should settle on one and stick to it. And since the name is **SML**FILES, I think that we do **not** want this one:
```makefile
SMLFILES   = $(patsubst %Script.sml,%Theory.uo,$(wildcard *.sml))
                                            ^^
                               because this should be "sml"
```

**Comment by andreaslindner** [comment]
Oh Yes, I see. I think I got confused by this once and now I didn't think completely. Initially I thought this issue was about something else :).
