### ISSUE TITLE
Should we remove BStmt_Declare?

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#63]
The question here is about the removal of `BStmt_Declare`. I tried to make a list of the points that we mentioned in today's meeting. Please comment on the Issue or edit this post.

**Knowing that**:
- Concrete assembly code doesn't have the notion of declare statements, and every variable is always declared and contains a value (i.e. registers and the memory are always defined).

**Advantages**:
- Simplifies some definitions:
  * Should remove the need of `bir_env_var_are_initialized` and cie.
  * Should remove the option in `bir_lookup_env`.

**Disadvantages**:
- Lost of genericity?

**Comment by andreaslindner** [comment]
Issue #27 is related to this. Should we have abbreviations like `bir_and_exp`? How are they to be used? What about interfaces between tools? Are abbreviations to be preferred? What about normal forms?

**Comment by didriklundberg** [comment]
> **Advantages**:
> 
>     * Simplifies some definitions:
>       
>       * Should remove the need of `bir_env_var_are_initialized` and cie.

We are not really there yet. From our discussions last time, removing declaration will allow us to remove the possibility of having variables with a type but no value in the variable environment (when you declare a variable, you add a variable of some type but no value to the variable environment). Let's look at `bir_env_var_is_initialised_def`:

```
val bir_env_var_is_initialised_def = Define `
  (bir_env_var_is_initialised env var <=>
  (?v. (bir_env_lookup (bir_var_name var) env = SOME (bir_var_type var, SOME v)) /\
         (type_of_bir_val v = SOME (bir_var_type var))))`;
```

* Looking up the variable with the name of `var` in `env` returns some value (`v` is _declared_ in the partial map), where the value is some `v` (`v` must also have been _initialised_ by assignment)
* The type of this `v` agrees with the type of `var`

Removing the possibility of no-value variables in the variable environment (which I think everyone has agreed makes sense so far) would enable us to simplify `bir_env_var_is_initialised_def` to something similar to the following:

```
val bir_env_var_is_initialised_def = Define `
  (bir_env_var_is_initialised env var <=>
  (?v. (bir_env_lookup (bir_var_name var) env = SOME (bir_var_type var, v) /\
         (type_of_bir_val v = SOME (bir_var_type var))))`;
```

So this would help us with one case split on `NONE` vs. `SOME v` in some proofs involving initialisation. We would still need to keep the `bir_env_vars_are_initialised` antecedents everywhere.

After the removal of `BStmt_Declare`, it would also be nice to have `env` store just values instead of tuples of types and values, and to have a `bir_val_t` sub-datatype which excludes `BVal_Unknown` (at least certainly in the case where we keep the partial map), as we discussed. 

For a possibility of removing the `bir_env_vars_are_initialised` antecedents altogether, we need to finish the discussion about ditching the partial map for a total map. I believe Roberto's current suggestion for the total map is the default value being some free variable, as opposed to `BVal_Unknown`. Either way, we need to change the domain to a tuple of name and type if we want to avoid usage of `bir_env_vars_are_initialised` for type agreement.

> Issue #27 is related to this. Should we have abbreviations like `bir_and_exp`? How are they to be used? What about interfaces between tools? Are abbreviations to be preferred? What about normal forms?

I think this is a significant change which deserves an issue of its own.

**Comment by totorigolo** [comment]
I meant "remove the need for initialization", since actual hardware registers and memories are in facts always initialized. I agree that this would not remove the need for an antecedent, but I think that it should be renamed.

**Comment by didriklundberg** [comment]
Question: why did we initially use `BVal_Unknown` instead of an option type for values, where `NONE` means an unknown value?

**Comment by didriklundberg** [comment]
To summarize the changes:

1. Remove the `BStmt_Declare` from syntax (and fix results from this)

**Comment by totorigolo** [comment]
> Related question: why did we initially use `BVal_Unknown` instead of an option type for values, where `NONE` means an unknown value?

That's as far as I can go:

https://github.com/kth-step/HolBA/commit/00dd4c762c8b224af902de80ad1c51a5eb199d60#diff-197d7b2f069eafa671537a634b5b6b27R53

It's been there since the very beginning in (what would become) HolBA because it's how it's done in BIL. Also maybe because it's less convenient to use monads in HOL4?

**Comment by didriklundberg** [comment]
To summarize the suggested changes:

1. Remove the `BStmt_Declare` from `bir_stmt_basic_t` datatype
2. Make the `option bir_val_t` in the return tuple of the variable environment a `bir_val_t` instead
3. Remove the `bir_type_t` from the return tuple of the variable environment
4. Switch the variable environment partial map for a total map (adding a `bir_type_t` as argument)?

Every step would also involve fixing the all the resulting consequences of the change. Do we want to do this all at once, or incrementally?
